export default {
  "الضمائر": require('./Image/0.png'),
  "أنا": require('./Image/0/0.png'),
  "أَنْتَ": require('./Image/0/1.png'),
  "أَنْتِ": require('./Image/0/2.png'),
  "هُوَ": require('./Image/0/3.png'),
  "هِيَ": require('./Image/0/4.png'),
  "أَنْتُمَا": require('./Image/0/5.png'),
  "هُمَا": require('./Image/0/6.png'),
  "نَحْنُ": require('./Image/0/7.png'),
  "أَنْتُمْ": require('./Image/0/8.png'),
  "أَنْتُنَّ": require('./Image/0/9.png'),
  "هُمْ": require('./Image/0/10.png'),
  "هُنَّ": require('./Image/0/11.png'),
  //الأفعال
  
  "الأفعال": require('./Image/1.png'),
  "أُرِيدُ أَنْ": require('./Image/1/0.png'),
  "أَكُلَ": require('./Image/1/1.png'),
  "أَشْرُبَ": require('./Image/1/2.png'),
  "أَخْرُجْ": require('./Image/1/3.png'),
  "أَكْتُبْ": require('./Image/1/4.png'),
  "أَجْلِسْ": require('./Image/1/5.png'),
  "أَنَامْ": require('./Image/1/6.png'),
  "أَقْرَأْ": require('./Image/1/7.png'),
  "أَلْعَبْ": require('./Image/1/8.png'),
 //الطعام
 "الطعام": require('./Image/2.png'),
 "فُطُورْ": require('./Image/2/0.png'),
 "غَدَاءْ": require('./Image/2/1.png'),
 "عَشَاءْ": require('./Image/2/2.png'),
 "خُبْزْ": require('./Image/2/3.png'),
 "زُبْدَّةْ": require('./Image/2/4.png'),
 "جُبْنَةْ": require('./Image/2/5.png'),
 "كَعْكَةْ": require('./Image/2/6.png'),
 "شُكُولَاطَةْ": require('./Image/2/7.png'),
 "سَلَطَةْ": require('./Image/2/8.png'),
 "حَسَاءْ": require('./Image/2/9.png'),
 "يَاغُورْتْ": require('./Image/2/10.png'),
 "حَلْوَّى": require('./Image/2/11.png'),
  //مشروبات
  "مشروبات": require('./Image/3.png'),
  "مَاءْ": require('./Image/3/0.png'),
  "عَصِيرْ": require('./Image/3/1.png'),
  "قَهْوَةْ": require('./Image/3/2.png'),
  "حَلِيبْ": require('./Image/3/3.png'),
  //خضراوات
  "خضراوات": require('./Image/4.png'),
  "بَطَاطِسْ": require('./Image/4/0.png'),
  "بَصَلْ": require('./Image/4/1.png'),
  "جَزَرْ": require('./Image/4/2.png'),
  "خِيَارْ": require('./Image/4/3.png'),
  "بَاذِنْـجَانْ": require('./Image/4/4.png'),
  "بَازِلَاءْ": require('./Image/4/5.png'),
  "فِلْفِلْ": require('./Image/4/6.png'),
  "فِجْلْ": require('./Image/4/7.png'),
  "يَقْطِينْ": require('./Image/4/8.png'),
  "بْرُوكْلِي": require('./Image/4/9.png'),
  //فواكه
  "فواكه": require('./Image/5.png'),
  "تُفَاحْ": require('./Image/5/0.png'),
  "مَوْزْ": require('./Image/5/1.png'),
  "عِنَبْ": require('./Image/5/2.png'),
  "بُرْتُقَالْ": require('./Image/5/3.png'),
  "فَرَاوِلَةْ": require('./Image/5/4.png'),
  "بِطِّيخْ": require('./Image/5/5.png'),
  "أَفُوكَادُو": require('./Image/5/6.png'),
  "تِينْ": require('./Image/5/7.png'),
  "لَيْمُونْ": require('./Image/5/8.png'),
  //مشاعر
  "مشاعر": require('./Image/6.png'),
  "سَعِيدْ": require('./Image/6/0.png'),
  "مُذْهِلْ": require('./Image/6/1.png'),
  "مُضْحِكْ": require('./Image/6/2.png'),
  "مُمِلْ": require('./Image/6/3.png'),
  "مُؤْلِمْ": require('./Image/6/4.png'),
  "مُحْزِنْ": require('./Image/6/5.png'),
  "غاضِبْ": require('./Image/6/6.png'),
  "حَسَنًا": require('./Image/6/7.png'),
  "نَعَمْ": require('./Image/6/8.png'),
  "لا": require('./Image/6/9.png'),
  //أمراض
 "أمراض": require('./Image/7.png'),
 "مَرِيضْ": require('./Image/7/0.png'),
 "صُدَاعْ": require('./Image/7/1.png'),
 "نَزْلَةُ بَرْدْ": require('./Image/7/2.png'),
 "كَسْرْ": require('./Image/7/3.png'),
 "أَلَمُ الأَسْنَانْ": require('./Image/7/4.png'),
 "غَثَيَّانْ": require('./Image/7/5.png'),
 "أَلَمْ فِي البَطْنِ": require('./Image/7/6.png'),
 "تَعَبْ": require('./Image/7/7.png'),
 //أدوات
 "أدوات": require('./Image/8.png'),
 "هَاتِفْ": require('./Image/8/0.png'),
 "حَاسُوبْ": require('./Image/8/1.png'),
 "سَمَّاعَاتْ": require('./Image/8/2.png'),
 "مِذْيَاعْ": require('./Image/8/3.png'),
 "كِتَابْ": require('./Image/8/4.png'),
 "مِحْفَظَةْ": require('./Image/8/5.png'),
 "مِسْطَرَةْ": require('./Image/8/6.png'),
 "قَلَمْ": require('./Image/8/7.png'),
 "سٌلَّمْ": require('./Image/8/8.png'),
 "كُرْسِيْ": require('./Image/8/9.png'),
 "كُرْسِيْ مُتَحَرِّكْ": require('./Image/8/10.png'),
 "نَظَارَاتْ": require('./Image/8/11.png'),
 "مِفْتَاحْ": require('./Image/8/12.png'),
 //حيوانات
 "حيوانات": require('./Image/9.png'),
 "أَرْنَبْ": require('./Image/9/0.png'),
 "أَسَدْ": require('./Image/9/1.png'),
 "أَفْعَى": require('./Image/9/2.png'),
 "بَطَةْ": require('./Image/9/3.png'),
 "بَانْدَا": require('./Image/9/4.png'),
 "بَقَرَةْ": require('./Image/9/5.png'),
 "بَعُوضَةْ": require('./Image/9/6.png'),
 "بُومَةْ": require('./Image/9/7.png'),
 "ثَعْلَبْ": require('./Image/9/8.png'),
 "حِمَارْ": require('./Image/9/9.png'),
 "حَمَامَةْ": require('./Image/9/10.png'),
 "خَيْلْ": require('./Image/9/11.png'),
 "دُبْ": require('./Image/9/12.png'),
 "دَجَاجَةْ": require('./Image/9/13.png'),
 "دِيكٌ": require('./Image/9/14.png'),
 "ذِئْبْ": require('./Image/9/15.png'),
 "سَمَكَةْ": require('./Image/9/16.png'),
 "فِيلْ": require('./Image/9/17.png'),
 "قِرْشْ": require('./Image/9/18.png'),
 "قِطَةْ": require('./Image/9/19.png'),
 "كَلْبْ": require('./Image/9/20.png'),
 "نَحْلَةْ": require('./Image/9/21.png'),
 "نَسْرْ": require('./Image/9/22.png'),
 //ألوان
 "ألوان": require('./Image/10.png'),
 "أحْمَرْ": require('./Image/10/0.png'),
 "أصْفَرْ": require('./Image/10/1.png'),
 "أخْضَرْ": require('./Image/10/2.png'),
 "أزْرَقْ": require('./Image/10/3.png'),
 "بُرْتُقَالِي": require('./Image/10/4.png'),
 "بَنَفْسَجِي": require('./Image/10/5.png'),
 "أَبْيَضْ": require('./Image/10/6.png'),
 "أَسْوَدْ": require('./Image/10/7.png'),
 
}
/*

 "": require('./Image/.png'),
 "": require('./Image//0.png'),
 "": require('./Image//1.png'),
 "": require('./Image//2.png'),
 "": require('./Image//3.png'),
 "": require('./Image//4.png'),
 "": require('./Image//5.png'),
 "": require('./Image//6.png'),
 "": require('./Image//7.png'),
 "": require('./Image//8.png'),
 "": require('./Image//9.png'),
 "": require('./Image//10.png'),
 "": require('./Image//11.png'),
 "": require('./Image//12.png'),
 "": require('./Image//13.png'),
 "": require('./Image//14.png'),
 "": require('./Image//15.png'),
 "": require('./Image//16.png'),
 "": require('./Image//17.png'),
 "": require('./Image//18.png'),
 "": require('./Image//19.png'),
 "": require('./Image//20.png'),
 "": require('./Image//21.png'),
 "": require('./Image//22.png'),

 */